var data = [
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/4/40/Torpedo.png",
    ItemName: "Torpedo",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$750,000",
    CurrentValue: "$45,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Torpedo"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/e/ed/ArachnidHD.png",
    ItemName: "Arachnid",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$750,000",
    CurrentValue: "$22,500,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Arachnid"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/0/04/Beam_Hybrid_HD.png",
    ItemName: "Beam Hybrid",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$100,000",
    CurrentValue: "$15,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Beam_Hybrid"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/a/a6/BugattiHD.png",
    ItemName: "Brulee",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$500,000",
    CurrentValue: "$7,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Brulee"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/f/f8/JB8HD.png",
    ItemName: "JB8",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$200,000",
    CurrentValue: "$5,500,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/JB8"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/b/b9/BeignetHD.png",
    ItemName: "Beignet",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$500,000",
    CurrentValue: "$5,400,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Beignet"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/3/37/MoltenHD.png",
    ItemName: "M12 Molten",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$599,000",
    CurrentValue: "$5,300,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/M12_Molten"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c5/RaptorHD.png",
    ItemName: "Raptor",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$150,000",
    CurrentValue: "$5,000,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Raptor"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/a/ae/MacaronTransparent.png",
    ItemName: "Macaron",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$0 at season 10 level 10",
    CurrentValue: "$3,000,000",
    Unobtainable: "Obtainable",
    Demand: "10/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Macaron"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/6/6d/IcebreakerHD.png",
    ItemName: "Icebreaker",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$0 at Season 7 level 10",
    CurrentValue: "$2,700,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Icebreaker"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c0/CelsiorHD.png",
    ItemName: "Celsior",
    Category: "Vehicle",
    Subcategory: "Aircraft",
    ReleasePrice: "$0 at Season 8 Level 10",
    CurrentValue: "$2,500,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Celsior"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c0/CelsiorHD.png",
    ItemName: "Agent",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$600,000",
    CurrentValue: "$2,500,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Agent"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/7/7d/ToreroHD.png",
    ItemName: "Torero",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$599,000",
    CurrentValue: "$2,000,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Torero"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c8/Airtail_HD.png",
    ItemName: "Air Tail",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$600,000",
    CurrentValue: "$2,000,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Airtail"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/d/db/FlyingEggHD.png",
    ItemName: "Crew Capsule",
    Category: "Vehicle",
    Subcategory: "Aircraft",
    ReleasePrice: "$0 at Season 2 Level 10",
    CurrentValue: "$1,500,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Crew_Capsule"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/e/e0/Fatvoltnoback.png",
    ItemName: "Volt 4X4",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$0 at Season 3 Level 10",
    CurrentValue: "$1,400,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Volt_4x4"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/a/a3/RattlerTransparent.png",
    ItemName: "Rattler",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$0 at Season 4 Level 10",
    CurrentValue: "$1,400,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Rattler"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/e/e2/Banana_car.png",
    ItemName: "Bannana Car",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$0 at Season 5 Level 10",
    CurrentValue: "$1,300,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Banana_Car"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c2/Jackrabbit.png",
    ItemName: "Jackrabbit",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$0 at Season 9 Level 8",
    CurrentValue: "$1,000,000",
    Unobtainable: "Unobtainable",
    Demand: "4/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Jackrabbit"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/e/e2/MightyHD.png",
    ItemName: "Mighty",
    Category: "Vehicle ",
    Subcategory: "General",
    ReleasePrice: "$25,000",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "3/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Mighty"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/7/7a/SteedHD.png",
    ItemName: "Steed",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$50,000",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "3/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Steed"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c8/PoshHD.png",
    ItemName: "Posh",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$70,000",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "3/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Posh"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/b/b4/SUVHD.png",
    ItemName: "SUV",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$40,000",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "3/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/SUV"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/8/88/Classic_Icon.png",
    ItemName: "Classic ",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$50,000",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "3/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Classic"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c9/ConceptHD.png",
    ItemName: "Concept",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$2,500,000",
    CurrentValue: "$2,500,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Concept"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/4/40/BHawkHD.png",
    ItemName: "Black Hawk",
    Category: "Vehicle",
    Subcategory: "Aircraft",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Black_Hawk"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/b/b4/Revampvoltnew.png",
    ItemName: "Volt Bike",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Volt"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/3/38/Dronee.png",
    ItemName: "Drone",
    Category: "Vehicle",
    Subcategory: "Aircraft",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Drone"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/f/fd/TrailblazerNoBack.png",
    ItemName: "Trailblazer",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Trailblazer"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/d/d1/JetHD.png",
    ItemName: "Jet",
    Category: "Vehicle",
    Subcategory: "Aircraft",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Jet"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/2/2c/TankHD.png",
    ItemName: "Tank",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Tank"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/2/2b/Revamped_Monster_HD.png",
    ItemName: "Monster Truck",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Monster_Truck"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/e/ec/Sloopnoback.png",
    ItemName: "Sloop",
    Category: "Vehicle",
    Subcategory: "Watercraft",
    ReleasePrice: "$1,000,000",
    CurrentValue: "$1,000,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Sloop"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/cd/Roadsterr.png",
    ItemName: "Roadster",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$600,000",
    CurrentValue: "$600,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Roadster"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/f/fb/Eclaire.png",
    ItemName: "Eclaire",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$599,000",
    CurrentValue: "$500,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Eclaire"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/9/91/UFOHD.png",
    ItemName: "UFO",
    Category: "Vehicle",
    Subcategory: "Aircraft",
    ReleasePrice: "$500,000",
    CurrentValue: "$500,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/UFO"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/9/95/SentinelHD.png",
    ItemName: "Sentinel",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$250,000",
    CurrentValue: "$250,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Sentinel"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/7/7d/StallionHD.png",
    ItemName: "Stallion",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$200,000",
    CurrentValue: "$200,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Stallion"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/9/90/StuntHD.png",
    ItemName: "Stunt",
    Category: "Vehicle",
    Subcategory: "Aircraft",
    ReleasePrice: "$200,000",
    CurrentValue: "$200,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Stunt"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/4/40/Ray9HD.png",
    ItemName: "Ray 9",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$199,000",
    CurrentValue: "$199,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Ray_9"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/0/00/Deloreann.png",
    ItemName: "Delorean",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$175,000",
    CurrentValue: "$175,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Delorean"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/5/5b/FiretruckHD.png",
    ItemName: "Firetruck",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$175,000",
    CurrentValue: "$175,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Firetruck"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/2/2a/Surus_HD.png",
    ItemName: "Surus",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$109,000",
    CurrentValue: "$109,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Surus"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/7/72/CybertruckBetterAnglePoseNoGreenScreenlines.png",
    ItemName: "Cybertruck",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$100,000",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Cybertruck"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/5/5b/Remodelled_Lamborghini.png",
    ItemName: "La Matador",
    Category: "Vehicle",
    Subcategory: "Super",
    ReleasePrice: "$100,000",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/La_Matador"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/9/97/AmbulanceHD.png",
    ItemName: "Ambulance",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$90,000",
    CurrentValue: "$90,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Ambulance"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/6/63/TTTransparenttemporary.png",
    ItemName: "Tow Truck",
    Category: "Vehicle",
    Subcategory: "Special",
    ReleasePrice: "$80,000",
    CurrentValue: "$80,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Tow_Truck"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/b/b1/Anattempt.png",
    ItemName: "The Camper",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$79,000",
    CurrentValue: "$79,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Camper"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/b/bf/Challenger.png",
    ItemName: "Challenger",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$59,000",
    CurrentValue: "$59,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Challenger"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/2/2d/BoxerHD.png",
    ItemName: "Boxer",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$55,000",
    CurrentValue: "$55,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Boxer"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/5/5a/ATVHD.png",
    ItemName: "ATV",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$50,000",
    CurrentValue: "$50,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/ATV"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/6/6f/BadgerHD.png",
    ItemName: "Badger",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$45,000",
    CurrentValue: "$45,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Badger"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/a/a7/Patrolnoback.png",
    ItemName: "Patrol",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$45,000",
    CurrentValue: "$45,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Patrol"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/f/f7/DuneBuggyHD.png",
    ItemName: "Dune Buggy",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$45,000",
    CurrentValue: "$45,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Dunebuggy"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/9/9a/DirtBikeHD.png",
    ItemName: "Dirtbike",
    Category: "Vehicle",
    Subcategory: "Offroad",
    ReleasePrice: "$35,000",
    CurrentValue: "$35,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Dirtbike"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/e/e5/Cruisernoback.png",
    ItemName: "Cruiser ",
    Category: "Vehicle",
    Subcategory: "Watercraft",
    ReleasePrice: "$35,000",
    CurrentValue: "$35,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Cruiser"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/6/6d/InterrogatorBetterAngleBetterPoseNoGreenScreenLines.png",
    ItemName: "Interrorgator",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$30,000",
    CurrentValue: "$30,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Interrogator"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/c4/RayHD.png",
    ItemName: "Ray",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$25,000",
    CurrentValue: "$25,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Vin_Ray"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/8/8e/Jetski_HD.png",
    ItemName: "Jet Ski",
    Category: "Vehicle",
    Subcategory: "Watercraft",
    ReleasePrice: "$25,000",
    CurrentValue: "$25,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Jet_Ski"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/6/6d/Model3BetterAngleBetterPoseNoBackground.png",
    ItemName: "Model 3",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$16,000",
    CurrentValue: "$16,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Model_3"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/c/cb/Deja.png",
    ItemName: "Deja",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$10,000",
    CurrentValue: "$10,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Deja"
  },
  {
    ImgLink: "https://static.wikia.nocookie.net/rblx-jailbreak/images/d/dd/Newpickupinfobox.png",
    ItemName: "Pickup",
    Category: "Vehicle",
    Subcategory: "General",
    ReleasePrice: "$9,000",
    CurrentValue: "$9,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "https://jailbreak.fandom.com/wiki/Pickup"
  },
  {
    ImgLink: "",
    ItemName: "Gold",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "Given to players on first week of release",
    CurrentValue: "$3,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Vanta Black",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Season 2 Level 5",
    CurrentValue: "$2,000,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Radiant Yellow",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 when nuked from 5/3/2020 to 6/4/2021",
    CurrentValue: "$1,500,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Radiant Orange",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 when nuked from 6/4/2021 to 1/7/2022",
    CurrentValue: "$1,250,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Radiant Ice",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 when nuked from 1/7/2022 to 6/4/2022",
    CurrentValue: "$750,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Radiant Green",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 when nuked from 1/7/2022 to present",
    CurrentValue: "$500,000",
    Unobtainable: "Obtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Hot Orange",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$250,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Super Lime",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$250,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Deep Purple",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$250,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Fall Chrome",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$250,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Chrome",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$1,000 after getting VIP",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Black",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Red",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "White",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Violet",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Matte",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Blue",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Cyan",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Sand",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Grey",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Green",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Gray? (Check)",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Orange",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Purple",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Pink",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pink",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Yellow",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pastel Brown",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Forest Green",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Blue",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Green",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Orange",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Yellow",
    Category: "Color",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at Garage",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Checker",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "Given to players who bought the car chassis demo",
    CurrentValue: "$6,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Pixel",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "Given to players who played jailbreak when it was realeased from beta",
    CurrentValue: "$2,500,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Armor",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "Use code wewilltakeover during the alien event in 2019",
    CurrentValue: "$2,000,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Orange Pixel",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "Was given to players who reached level 50 criminal in og season 2",
    CurrentValue: "$1,000,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Blue Pixel",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "Was given to players who reached level 50 police in og season 2",
    CurrentValue: "$1,000,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Fire",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 1 level 8",
    CurrentValue: "$900,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Galactic Carbon",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 2 level 8",
    CurrentValue: "$900,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Snow Storm",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 1 level 5",
    CurrentValue: "$900,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Digital Confetti",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 3 level 4",
    CurrentValue: "$750,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Drip",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 5 level 8",
    CurrentValue: "$750,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Earthquake",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 4 level 5",
    CurrentValue: "$700,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Crimson Racer",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 6 level 8",
    CurrentValue: "$650,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Flaming",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 to players in the top 5% of season 6",
    CurrentValue: "$650,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Gulf",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 to players in the top 10% of season 6",
    CurrentValue: "$600,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Winter Camo",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 to players in the top 1% in season 7",
    CurrentValue: "$600,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Black Ice",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 7 level 8",
    CurrentValue: "$550,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Circuits",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 8 level 8",
    CurrentValue: "$400,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Old Town Road",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 9 level 10",
    CurrentValue: "$400,000",
    Unobtainable: "Unobtainable",
    Demand: "3/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "White Marble",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 10 level 8",
    CurrentValue: "$300,000",
    Unobtainable: "Obtainable",
    Demand: "3/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Bacon",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Tiger",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Hotdog",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "3/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Money",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Wavy",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Earth",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Lightning",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Field",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Glowing Yellow",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Ladybug",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$100,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Peach",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$100,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "ClassicVar1",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$50,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "ClassicVar2",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$50,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "ClassicVar3",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$50,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Speed",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$50,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Volt",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$50,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "javascript:void(0)"
  },
  {
    ImgLink: "",
    ItemName: "Camo",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$50,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Wireframe",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$45,000",
    CurrentValue: "$45,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Galaxy",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$40,000",
    CurrentValue: "$40,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Donut",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$40,000",
    CurrentValue: "$40,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Scorch",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$40,000",
    CurrentValue: "$40,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Diamond",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$40,000",
    CurrentValue: "$40,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Zebra",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$40,000",
    CurrentValue: "$40,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Candy Cane",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$40,000",
    CurrentValue: "$40,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Volcano",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$39,000",
    CurrentValue: "$39,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Lines",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$35,000",
    CurrentValue: "$35,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Ball",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Galaxy Wave",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Frit",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Swirl",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Ice",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Two Sided",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Taxi",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Frost",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$10,000",
    CurrentValue: "$10,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Racer",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$10,000",
    CurrentValue: "$10,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Cow",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$4,000",
    CurrentValue: "$4,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Rainbow",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$4,000",
    CurrentValue: "$4,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Police",
    Category: "Texture",
    Subcategory: "#N/A",
    ReleasePrice: "$2,000",
    CurrentValue: "$2,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Spinners",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Available in safes from 5/27/17 to 6/4/17",
    CurrentValue: "$55,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Brickset",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Came in a code with jailbreak season 4 inmate toy",
    CurrentValue: "$20,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Hypno",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "? % with Legendary Safe in 2018 ($30,000)",
    CurrentValue: "$5,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Snowflake",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "? % with Legendary Safe in 2017 ($30,000)",
    CurrentValue: "$5,000,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Star Badge",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "10,000 in og season 1",
    CurrentValue: "$2,500,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Spider Leg",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Cost 10,000 in og season 1",
    CurrentValue: "$2,000,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Void",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 1 level 9",
    CurrentValue: "$2,000,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Bull",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 1 level 6",
    CurrentValue: "$1,000,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Planetary",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 2 level 3",
    CurrentValue: "$900,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Blue Eyes",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by reaching level 40 police team in season 3 and buying for 5,000",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Red Eyes",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by reaching level 40 criminal team in season 3 and buying for 5,000",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Distorted",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by reaching level 20 police team in season 3 and buying for 5,000",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Nemesis",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by reaching level 20 criminal team in season 3 and buying for 5,000",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Live 2020",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by attending the 2020 live event",
    CurrentValue: "$800,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Compass",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 4 level 8",
    CurrentValue: "$800,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Rtx",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 5 level 9",
    CurrentValue: "$750,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Bonded",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by putting the soccer ball on the map into the soccer net",
    CurrentValue: "$750,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Center Lock",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 6 level 7",
    CurrentValue: "$700,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Retro Racer",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 6 level 2",
    CurrentValue: "$650,000",
    Unobtainable: "Unobtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Snow Face",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 7 level 9",
    CurrentValue: "$650,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Icicle",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 7 level 5",
    CurrentValue: "$600,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Trion",
    Category: "RIm",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 8 level 2",
    CurrentValue: "$600,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Ionize",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 8 level 7",
    CurrentValue: "$600,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Energized",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 8 top 2 percent",
    CurrentValue: "$600,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Beadlocks",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 9 level 6",
    CurrentValue: "$400,000",
    Unobtainable: "Unobtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Iron Rock",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 9 level 5",
    CurrentValue: "$400,000",
    Unobtainable: "Unobtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Diamond Engrave",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 10 level 9",
    CurrentValue: "$300,000",
    Unobtainable: "Obtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Roll-X",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 10 level 4",
    CurrentValue: "$200,000",
    Unobtainable: "Obtainable",
    Demand: "3/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "4 Billion",
    Category: "Rim ",
    Subcategory: "#N/A",
    ReleasePrice: "Cost 2,000 when jailbreak hit 4 billion visits",
    CurrentValue: "$200,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Piggy",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "                       Getting killed by piggy in the sewers from 5/3/2020 to 2/6/2021    ",
    CurrentValue: "$200,000",
    Unobtainable: "Unobtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Soccer",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "              Pushing the giant soccer ball into the goal from 3/7/2019 to 4/4/2020",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Flower",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Spike",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "? % Chance with Legendary Safe ($30,000)",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "3/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Bloxy",
    Category: "RIm",
    Subcategory: "#N/A",
    ReleasePrice: "$25,000",
    CurrentValue: "$25,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Cyclone",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$10,000",
    CurrentValue: "$10,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Billion",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$10,000",
    CurrentValue: "$10,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: ""
  },
  {
    ImgLink: "",
    ItemName: "Money",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$5,000",
    CurrentValue: "$5,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Jet",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$1,000",
    CurrentValue: "$1,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Star",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$1,000",
    CurrentValue: "$1,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Halo",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$1,000",
    CurrentValue: "$1,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Turbine",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$1,000",
    CurrentValue: "$1,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Arachnid",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$1,000",
    CurrentValue: "$1,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Blade",
    Category: "Rim",
    Subcategory: "#N/A",
    ReleasePrice: "$0",
    CurrentValue: "$0",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Spare Tire",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Buy extra storage gamepass",
    CurrentValue: "$25,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Brickset",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Came in a code with jailbreak season 4 inmate toy",
    CurrentValue: "$20,000,000",
    Unobtainable: "Unobtainable",
    Demand: "10/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Dual Flags",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by pushing giant soccer ball into goal from 2018-19",
    CurrentValue: "$3,000,000",
    Unobtainable: "Unobtainable",
    Demand: "9/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Thrusters",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 2 level 9",
    CurrentValue: "$1,500,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Blue Chute",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Reach level 25 on police team during season 4",
    CurrentValue: "$1,250,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Orange Chute",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Reach level 25 on criminal team during season 4",
    CurrentValue: "$1,250,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "UFO",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Reach level 50",
    CurrentValue: "$1,200,000",
    Unobtainable: "Unobtainable",
    Demand: "8/10",
    WikiLink: ""
  },
  {
    ImgLink: "",
    ItemName: "5Star",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Reach level 45 on police team",
    CurrentValue: "$1,000,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Eightleg",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Reach level 45 on criminal team",
    CurrentValue: "$1,000,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Starwing",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 2 level 4",
    CurrentValue: "$900,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Volt Wing",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 3 level 9",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "2 Billion",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained through safes in 2018",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Triple Fin",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Reach level 15 on police team",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Robowing",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Reach level 15 on criminal team",
    CurrentValue: "$850,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "3 Billion",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Use code THREEBILLIONVISITS when jailbreak hit 3 billion visits",
    CurrentValue: "$800,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Deathtrap",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 4 level 6",
    CurrentValue: "$750,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Tikitorch",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 4 level 9",
    CurrentValue: "$750,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Tuner",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 5 level 6",
    CurrentValue: "$700,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Clickbait",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 5 level 3",
    CurrentValue: "$700,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Jdm",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 6 level 6",
    CurrentValue: "$650,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Velocity",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 6 level 5",
    CurrentValue: "$650,000",
    Unobtainable: "Unobtainable",
    Demand: "6/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Snow Log",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 7 level 4",
    CurrentValue: "$500,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Snow Shovel",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 7 level 7",
    CurrentValue: "$500,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Overdrive",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 8 level 4",
    CurrentValue: "$450,000",
    Unobtainable: "Unobtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Mecha Arm",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 8 level 5",
    CurrentValue: "$450,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: " Bicycle Rack",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 9 level 9",
    CurrentValue: "$450,000",
    Unobtainable: "Unobtainable",
    Demand: "5/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Glider",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 9 level 7",
    CurrentValue: "$300,000",
    Unobtainable: "Unobtainable",
    Demand: "4/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Cash Spitter",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 10 level 7 with the season pass",
    CurrentValue: "$300,000",
    Unobtainable: "Obtainable",
    Demand: "7/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Travel Case",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 9 level 2",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Live Glider",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Jump on the meteor during the 2022 live event",
    CurrentValue: "$250,000",
    Unobtainable: "Unobtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Trophy Wings ",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$0 at season 10 level 2",
    CurrentValue: "$200,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Dino Bone",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by putting the soccer ball on the map into the soccer net",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "2/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Eternal Flame",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "Obtained by completing the tomb robbery for the first time",
    CurrentValue: "$100,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "5B Flags",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$50,000",
    CurrentValue: "$50,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Batwings",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$50,000",
    CurrentValue: "$50,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Park Bench",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$30,000",
    CurrentValue: "$30,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Tailfin",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$25,000",
    CurrentValue: "$25,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Tail Arch",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Boomerang",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$20,000",
    CurrentValue: "$20,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Arch",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$15,000",
    CurrentValue: "$15,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Tiny Wing",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$15,000",
    CurrentValue: "$15,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Rocket",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$10,000",
    CurrentValue: "$10,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Classic",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$7,500",
    CurrentValue: "$7,500",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  },
  {
    ImgLink: "",
    ItemName: "Block Wing",
    Category: "Spoiler",
    Subcategory: "#N/A",
    ReleasePrice: "$5,000",
    CurrentValue: "$5,000",
    Unobtainable: "Obtainable",
    Demand: "1/10",
    WikiLink: "#N/A"
  }
];